GET http://localhost:3000/point

###
// BATER PONTO: Os clockType são "Clock In" e "Clock Out".
// O primeiro tem que ser "Clock In" e ir intercalando com "Clock Out"
POST http://localhost:3000/clockings
content-type: application/json

{
  "clockType":"Clock In",
  "userId": "12345678"
}